"""
Email service - SendGrid + Jinja2 templates
Sends automated emails from agents
"""
import logging
from datetime import datetime
from typing import Optional
from jinja2 import Environment, BaseLoader

from core.config import settings

logger = logging.getLogger(__name__)

# Jinja2 email templates
KPI_ALERT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px; }
  .container { background: white; padding: 30px; border-radius: 8px; max-width: 700px; margin: 0 auto; }
  .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 15px; margin-bottom: 20px; }
  .header h1 { color: #1e3a5f; margin: 0; font-size: 24px; }
  .alert-card { background: #fff5f5; border-left: 4px solid #e53e3e; padding: 15px; margin: 10px 0; border-radius: 4px; }
  .warning-card { background: #fffaf0; border-left: 4px solid #ed8936; padding: 15px; margin: 10px 0; border-radius: 4px; }
  .footer { margin-top: 30px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }
  .badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; }
  .badge-critical { background: #fed7d7; color: #9b2c2c; }
  .badge-warning { background: #feebc8; color: #9c4221; }
</style></head>
<body>
<div class="container">
  <div class="header">
    <h1>⚠️ Summit Growth Partners - KPI Alert</h1>
    <p style="color:#666; margin: 5px 0 0">Automated Alert | {{ timestamp }}</p>
  </div>
  <p>The FP&A monitoring system has detected the following KPI issues requiring your attention:</p>
  {% for alert in alerts %}
  <div class="{{ 'alert-card' if alert.severity == 'critical' else 'warning-card' }}">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
      <strong>{{ alert.company_name }} — {{ alert.kpi }}</strong>
      <span class="badge badge-{{ alert.severity }}">{{ alert.severity.upper() }}</span>
    </div>
    <p style="margin: 0; color: #555;">{{ alert.message }}</p>
  </div>
  {% endfor %}
  <p style="margin-top: 20px;">Please review the <a href="http://localhost:3000/kpis" style="color: #1e3a5f;">KPI Dashboard</a> for detailed analysis and recommended actions.</p>
  <div class="footer">
    <p>This email was automatically generated by the Summit Growth Partners FP&A Platform.<br>
    © {{ year }} Summit Growth Partners</p>
  </div>
</div>
</body>
</html>
"""

REFORECAST_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px; }
  .container { background: white; padding: 30px; border-radius: 8px; max-width: 700px; margin: 0 auto; }
  .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 15px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #1e3a5f; color: white; padding: 10px; text-align: left; }
  td { padding: 10px; border-bottom: 1px solid #eee; }
  tr:hover { background: #f9f9f9; }
  .footer { margin-top: 30px; font-size: 12px; color: #999; }
</style></head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 Monthly Reforecast Summary</h1>
    <p style="color:#666;">Summit Growth Partners | {{ month_year }}</p>
  </div>
  <p>The automated monthly reforecast has been completed for all 6 portfolio companies.</p>
  <table>
    <thead><tr><th>Company</th><th>Annual Forecast</th><th>YoY Growth</th><th>Annual OpEx</th></tr></thead>
    <tbody>
    {% for r in results %}
    <tr>
      <td><strong>{{ r.company }}</strong></td>
      <td>${{ "{:,.0f}".format(r.annual_forecast) }}</td>
      <td>{{ "{:.1f}".format(r.yoy_growth * 100) }}%</td>
      <td>${{ "{:,.0f}".format(r.total_opex) }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  <p><a href="http://localhost:3000/forecasts" style="color: #1e3a5f;">View Full Forecasts →</a></p>
  <div class="footer">Automatically generated by Summit Growth Partners FP&A Platform</div>
</div>
</body>
</html>
"""

WEEKLY_SUMMARY_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px; }
  .container { background: white; padding: 30px; border-radius: 8px; max-width: 700px; margin: 0 auto; }
  .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 15px; margin-bottom: 20px; }
  .insights { background: #f8fafc; padding: 20px; border-radius: 6px; line-height: 1.7; }
  .footer { margin-top: 30px; font-size: 12px; color: #999; }
</style></head>
<body>
<div class="container">
  <div class="header">
    <h1>📈 Weekly Portfolio Insights</h1>
    <p style="color:#666;">Summit Growth Partners | Week of {{ date }}</p>
  </div>
  <div class="insights">{{ insights | replace('\n', '<br>') }}</div>
  <p style="margin-top: 20px;"><a href="http://localhost:3000" style="color: #1e3a5f;">View Portfolio Dashboard →</a></p>
  <div class="footer">Automatically generated by Summit Growth Partners FP&A Platform</div>
</div>
</body>
</html>
"""


jinja_env = Environment(loader=BaseLoader())


def _render(template_str: str, **ctx) -> str:
    tmpl = jinja_env.from_string(template_str)
    return tmpl.render(**ctx)


async def _send_email(to_email: str, subject: str, html_body: str, email_type: str = "general"):
    """Send email via SendGrid or log if no API key."""
    # Log to DB
    from core.database import AsyncSessionLocal
    from models.financial import EmailLog

    async with AsyncSessionLocal() as session:
        log = EmailLog(
            to_email=to_email,
            subject=subject,
            body_preview=html_body[:500],
            email_type=email_type,
            status="sent" if settings.sendgrid_api_key else "logged",
        )
        session.add(log)
        await session.commit()

    if not settings.sendgrid_api_key:
        logger.info(f"[EMAIL LOG - no SendGrid key] To: {to_email} | Subject: {subject}")
        return

    try:
        import sendgrid
        from sendgrid.helpers.mail import Mail

        sg = sendgrid.SendGridAPIClient(api_key=settings.sendgrid_api_key)
        message = Mail(
            from_email=settings.from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_body,
        )
        sg.client.mail.send.post(request_body=message.get())
        logger.info(f"Email sent to {to_email}: {subject}")
    except Exception as e:
        logger.error(f"Email send failed: {e}")


async def send_kpi_alert_email(alerts: list[dict]):
    html = _render(
        KPI_ALERT_TEMPLATE,
        alerts=alerts,
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        year=datetime.utcnow().year,
    )
    await _send_email(
        to_email="cfo@summitgrowthpartners.com",
        subject=f"🚨 FP&A KPI Alert - {len(alerts)} Issues Detected",
        html_body=html,
        email_type="kpi_alert",
    )


async def send_reforecast_summary_email(results: list[dict]):
    html = _render(
        REFORECAST_TEMPLATE,
        results=results,
        month_year=datetime.utcnow().strftime("%B %Y"),
    )
    await _send_email(
        to_email="partners@summitgrowthpartners.com",
        subject=f"📊 Monthly Reforecast Complete - {datetime.utcnow().strftime('%B %Y')}",
        html_body=html,
        email_type="reforecast",
    )


async def send_weekly_summary_email(insights: str):
    html = _render(
        WEEKLY_SUMMARY_TEMPLATE,
        insights=insights,
        date=datetime.utcnow().strftime("%B %d, %Y"),
    )
    await _send_email(
        to_email="partners@summitgrowthpartners.com",
        subject=f"📈 Weekly Portfolio Insights - {datetime.utcnow().strftime('%b %d')}",
        html_body=html,
        email_type="weekly_summary",
    )


async def send_variance_alert_email(company_name: str, variance_data: dict):
    subject = f"⚠️ Material Variance Alert: {company_name}"
    html = f"""
    <div style="font-family: Arial; padding: 20px; max-width: 600px;">
        <h2 style="color: #1e3a5f;">Material Variance Alert</h2>
        <p><strong>Company:</strong> {company_name}</p>
        <p><strong>Revenue Variance:</strong> ${variance_data.get('revenue_variance', 0):,.0f} ({variance_data.get('revenue_variance_pct', 0)*100:.1f}%)</p>
        <p><strong>EBITDA Variance:</strong> ${variance_data.get('ebitda_variance', 0):,.0f}</p>
        <p><strong>Commentary:</strong> {variance_data.get('board_commentary', 'N/A')}</p>
        <p><a href="http://localhost:3000/variance" style="color: #1e3a5f;">View Full Variance Analysis →</a></p>
    </div>
    """
    await _send_email(
        to_email="cfo@summitgrowthpartners.com",
        subject=subject,
        html_body=html,
        email_type="variance_alert",
    )
