from fastapi import APIRouter, Depends, Response
from sqlalchemy.ext.asyncio import AsyncSession
from core.database import get_db

router = APIRouter()


@router.get("/pdf/{company_id}")
async def generate_pdf_report(company_id: str, db: AsyncSession = Depends(get_db)):
    """Generate PDF board pack for a company."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    import io
    from sqlalchemy import select
    from models.financial import FinancialRecord
    from models.company import Company

    # Get company info
    result = await db.execute(select(Company).where(Company.id == company_id))
    company = result.scalar_one_or_none()
    if not company:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Company not found")

    # Get financial data
    result = await db.execute(
        select(FinancialRecord)
        .where(FinancialRecord.company_id == company_id)
        .order_by(FinancialRecord.period.desc())
        .limit(100)
    )
    records = result.scalars().all()
    by_period: dict = {}
    for r in records:
        if r.period not in by_period:
            by_period[r.period] = {"period": r.period}
        by_period[r.period][r.metric] = r.value

    recent = sorted(by_period.values(), key=lambda x: x["period"], reverse=True)[:6]

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.75*inch, leftMargin=0.75*inch,
                             topMargin=inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph(f"Summit Growth Partners", styles["Heading1"]))
    story.append(Paragraph(f"Monthly Board Pack — {company.name}", styles["Heading2"]))
    story.append(Spacer(1, 0.2*inch))

    # Company overview
    story.append(Paragraph("Company Overview", styles["Heading3"]))
    story.append(Paragraph(
        f"<b>Industry:</b> {company.industry} | <b>Annual Revenue:</b> ${company.annual_revenue:,.0f} | "
        f"<b>Growth Rate:</b> {company.growth_rate*100:.0f}% | <b>Headcount:</b> {company.headcount}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.2*inch))

    # Financial table
    if recent:
        story.append(Paragraph("Financial Performance (Monthly)", styles["Heading3"]))
        table_data = [["Period", "Revenue", "Gross Profit", "EBITDA", "EBITDA Margin"]]
        for p in recent:
            rev = p.get("revenue", 0)
            gp = p.get("gross_profit", 0)
            ebitda = p.get("ebitda", 0)
            margin = f"{ebitda/rev*100:.1f}%" if rev else "N/A"
            table_data.append([
                p["period"],
                f"${rev:,.0f}",
                f"${gp:,.0f}",
                f"${ebitda:,.0f}",
                margin,
            ])

        table = Table(table_data, colWidths=[1.2*inch, 1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4f8")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)

    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(
        "This report was automatically generated by the Summit Growth Partners FP&A Platform.",
        styles["Normal"]
    ))

    doc.build(story)
    buffer.seek(0)

    return Response(
        content=buffer.read(),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={company_id}_board_pack.pdf"},
    )


@router.get("/excel/{company_id}")
async def export_excel(company_id: str, db: AsyncSession = Depends(get_db)):
    """Export financial model as Excel."""
    import io
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from sqlalchemy import select
    from models.financial import FinancialRecord
    from models.company import Company

    result = await db.execute(select(Company).where(Company.id == company_id))
    company = result.scalar_one_or_none()
    if not company:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Company not found")

    result = await db.execute(
        select(FinancialRecord)
        .where(FinancialRecord.company_id == company_id)
        .order_by(FinancialRecord.period)
    )
    records = result.scalars().all()
    by_period: dict = {}
    for r in records:
        if r.period not in by_period:
            by_period[r.period] = {}
        by_period[r.period][r.metric] = r.value

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Financial Model"

    # Header styling
    header_fill = PatternFill("solid", fgColor="1E3A5F")
    header_font = Font(color="FFFFFF", bold=True)
    metrics = ["revenue", "cogs", "gross_profit", "sales_marketing", "rd", "ga", "ebitda", "net_income"]
    periods = sorted(by_period.keys())

    ws.cell(1, 1, "Metric").font = header_font
    ws.cell(1, 1).fill = header_fill
    for col, period in enumerate(periods, 2):
        cell = ws.cell(1, col, period)
        cell.font = header_font
        cell.fill = header_fill

    for row, metric in enumerate(metrics, 2):
        ws.cell(row, 1, metric.replace("_", " ").title())
        for col, period in enumerate(periods, 2):
            val = by_period.get(period, {}).get(metric, 0)
            ws.cell(row, col, round(val, 0))

    ws.column_dimensions["A"].width = 20
    for col in range(2, len(periods) + 2):
        ws.column_dimensions[openpyxl.utils.get_column_letter(col)].width = 14

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    return Response(
        content=buffer.read(),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={company_id}_financial_model.xlsx"},
    )
